baseURL = 'https://isbrqu.github.io/trabalenguas-55/'
languageCode = "es"
theme = "anubis2"
title = "La Voz del 55 - Trabalenguas"


defaultContentLanguage = "es"
[languages]
  [languages.es]
    languageName = "Español"
    weight = 1

[author]
name = "Fioni & Aisaac"

[params]
colorThemeSwitcher = true
math = false
rssAsSocialIcon = true
social = [
  { id = "email", url = "example@example.com" },
  { id = "instagram", url = "https://www.instagram.com/radiolavozdel55" },
  { id = "youtube", url = "https://www.youtube.com/channel/UC3aRmAXFTsBbPNAaeVobQMw/playlists" }
]

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

[[menu.main]]
identifier = "home"
name = "Inicio"
url = "/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Etiquetas"
url = "/tags/"
weight = 3

[[menu.main]]
identifier = "archive"
name = "Archivados"
url = "/posts/"
weight = 4
